openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for Example
paths:
    /example:
        post:
            tags:
                - FooService
            summary: FooMethod FooService
            operationId: FooService#FooMethod
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/FooMethodRequestBody'
                        example:
                            External:
                                Field: Eos quisquam et nisi molestiae.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/FooMethodRequestBody'
                                example:
                                    - External:
                                        Field: Voluptates voluptates quia non.
                                    - External:
                                        Field: Voluptates voluptates quia non.
                            example:
                                - External:
                                    Field: Voluptates voluptates quia non.
                                - External:
                                    Field: Voluptates voluptates quia non.
                                - External:
                                    Field: Voluptates voluptates quia non.
                                - External:
                                    Field: Voluptates voluptates quia non.
components:
    schemas:
        ExternalType:
            type: object
            properties:
                Field:
                    type: string
                    example: Non omnis.
            example:
                Field: Numquam delectus ut excepturi dolorem autem.
            required:
                - Field
        FooMethodRequestBody:
            type: object
            properties:
                External:
                    $ref: '#/components/schemas/ExternalType'
            example:
                External:
                    Field: Eos quisquam et nisi molestiae.
tags:
    - name: FooService
