swagger: "2.0"
info:
    title: ""
    version: ""
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /example:
        post:
            tags:
                - FooService
            summary: FooMethod FooService
            operationId: FooService#FooMethod
            parameters:
                - name: FooMethodRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/FooServiceFooMethodRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/ExampleTypeResponse'
            schemes:
                - http
definitions:
    ExampleTypeResponse:
        title: ExampleTypeResponse
        type: object
        properties:
            External:
                $ref: '#/definitions/ExternalTypeResponse'
        example:
            External:
                Field: Voluptates voluptates quia non.
    ExternalTypeRequestBody:
        title: ExternalTypeRequestBody
        type: object
        properties:
            Field:
                type: string
                example: Facilis exercitationem qui.
        example:
            Field: Praesentium sed.
        required:
            - Field
    ExternalTypeResponse:
        title: ExternalTypeResponse
        type: object
        properties:
            Field:
                type: string
                example: Ut mollitia id similique.
        example:
            Field: Corrupti distinctio ut.
        required:
            - Field
    FooServiceFooMethodRequestBody:
        title: FooServiceFooMethodRequestBody
        type: object
        properties:
            External:
                $ref: '#/definitions/ExternalTypeRequestBody'
        example:
            External:
                Field: Eos quisquam et nisi molestiae.
