openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for Example
paths:
    /example:
        post:
            tags:
                - FooService
            summary: FooMethod FooService
            operationId: FooService#FooMethod
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/FooMethodRequestBody'
                        example:
                            DateField: "2009-08-25T06:53:12Z"
                            External:
                                Field: Ut mollitia id similique.
                            SecondExternal:
                                Field: Corrupti distinctio ut.
                            UintField: 10644113808551616344
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/FooMethodRequestBody'
                                example:
                                    - DateField: "1988-07-10T21:21:45Z"
                                      External:
                                        Field: Rerum aut atque animi.
                                      SecondExternal:
                                        Field: Et quisquam quia ab quia rerum.
                                      UintField: 11307322308777854749
                                    - DateField: "1988-07-10T21:21:45Z"
                                      External:
                                        Field: Rerum aut atque animi.
                                      SecondExternal:
                                        Field: Et quisquam quia ab quia rerum.
                                      UintField: 11307322308777854749
                                    - DateField: "1988-07-10T21:21:45Z"
                                      External:
                                        Field: Rerum aut atque animi.
                                      SecondExternal:
                                        Field: Et quisquam quia ab quia rerum.
                                      UintField: 11307322308777854749
                                    - DateField: "1988-07-10T21:21:45Z"
                                      External:
                                        Field: Rerum aut atque animi.
                                      SecondExternal:
                                        Field: Et quisquam quia ab quia rerum.
                                      UintField: 11307322308777854749
                            example:
                                - DateField: "1988-07-10T21:21:45Z"
                                  External:
                                    Field: Rerum aut atque animi.
                                  SecondExternal:
                                    Field: Et quisquam quia ab quia rerum.
                                  UintField: 11307322308777854749
                                - DateField: "1988-07-10T21:21:45Z"
                                  External:
                                    Field: Rerum aut atque animi.
                                  SecondExternal:
                                    Field: Et quisquam quia ab quia rerum.
                                  UintField: 11307322308777854749
                                - DateField: "1988-07-10T21:21:45Z"
                                  External:
                                    Field: Rerum aut atque animi.
                                  SecondExternal:
                                    Field: Et quisquam quia ab quia rerum.
                                  UintField: 11307322308777854749
components:
    schemas:
        ExternalType:
            type: object
            properties:
                Field:
                    type: string
                    example: Vel velit quod sint ut rem ea.
            example:
                Field: Vitae qui assumenda suscipit ut mollitia dolores.
            required:
                - Field
        FooMethodRequestBody:
            type: object
            properties:
                DateField:
                    type: string
                    example: "1982-10-11T05:43:45Z"
                    format: date-time
                External:
                    $ref: '#/components/schemas/ExternalType'
                SecondExternal:
                    $ref: '#/components/schemas/SecondExternalType'
                UintField:
                    type: integer
                    example: 13330659040426132812
            example:
                DateField: "2011-03-03T22:34:36Z"
                External:
                    Field: Ut mollitia id similique.
                SecondExternal:
                    Field: Corrupti distinctio ut.
                UintField: 1866741884742137221
            required:
                - DateField
                - UintField
        SecondExternalType:
            type: object
            properties:
                Field:
                    type: string
                    example: Aliquid eius ducimus doloremque incidunt asperiores.
            example:
                Field: Pariatur velit minima voluptatem dolores rerum.
tags:
    - name: FooService
