swagger: "2.0"
info:
    title: ""
    version: ""
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /example:
        post:
            tags:
                - FooService
            summary: FooMethod FooService
            operationId: FooService#FooMethod
            parameters:
                - name: FooMethodRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/FooServiceFooMethodRequestBody'
                    required:
                        - DateField
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/ExampleTypeResponse'
            schemes:
                - http
definitions:
    Bar:
        title: Bar
        type: object
        properties:
            Bar:
                type: integer
                example: 2959201625900554196
                format: int64
        example:
            Bar: 6075347245146661455
        required:
            - Bar
    ExampleTypeResponse:
        title: ExampleTypeResponse
        type: object
        properties:
            DateField:
                type: string
                example: "1981-05-05T04:08:06Z"
                format: date-time
            External:
                $ref: '#/definitions/ExternalTypeResponse'
            FieldWithExtension:
                $ref: '#/definitions/FieldWithExtensionResponse'
            SecondExternal:
                $ref: '#/definitions/SecondExternalTypeResponse'
        example:
            DateField: "1989-05-01T13:46:14Z"
            External:
                Field: Suscipit rerum aut atque animi ut et.
            FieldWithExtension:
                BarField:
                    Bar: 12728010016061705013
            SecondExternal:
                Field: Quia ab quia rerum.
        required:
            - DateField
    ExternalTypeRequestBody:
        title: ExternalTypeRequestBody
        type: object
        properties:
            Field:
                type: string
                example: Nihil qui aut.
        example:
            Field: Distinctio eligendi atque vel omnis molestiae occaecati.
        required:
            - Field
    ExternalTypeResponse:
        title: ExternalTypeResponse
        type: object
        properties:
            Field:
                type: string
                example: Iusto dolores.
        example:
            Field: Fugit autem sed.
        required:
            - Field
    FieldWithExtensionRequestBody:
        title: FieldWithExtensionRequestBody
        type: object
        properties:
            BarField:
                $ref: '#/definitions/Bar'
        example:
            BarField:
                Bar: 12728010016061705013
    FieldWithExtensionResponse:
        title: FieldWithExtensionResponse
        type: object
        properties:
            BarField:
                $ref: '#/definitions/Bar'
        example:
            BarField:
                Bar: 12728010016061705013
    FooServiceFooMethodRequestBody:
        title: FooServiceFooMethodRequestBody
        type: object
        properties:
            DateField:
                type: string
                example: "2001-10-05T16:36:22Z"
                format: date-time
            External:
                $ref: '#/definitions/ExternalTypeRequestBody'
            FieldWithExtension:
                $ref: '#/definitions/FieldWithExtensionRequestBody'
            SecondExternal:
                $ref: '#/definitions/SecondExternalTypeRequestBody'
        example:
            DateField: "2009-07-20T14:20:40Z"
            External:
                Field: Ut mollitia id similique.
            FieldWithExtension:
                BarField:
                    Bar: 12728010016061705013
            SecondExternal:
                Field: Corrupti distinctio ut.
        required:
            - DateField
    SecondExternalTypeRequestBody:
        title: SecondExternalTypeRequestBody
        type: object
        properties:
            Field:
                type: string
                example: Tempore quo quaerat aut et.
        example:
            Field: Est ea.
    SecondExternalTypeResponse:
        title: SecondExternalTypeResponse
        type: object
        properties:
            Field:
                type: string
                example: Voluptatibus aut qui.
        example:
            Field: Similique aut qui numquam veritatis repudiandae.
