openapi: 3.0.3
info:
    title: Goa API
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for Example
paths:
    /example:
        post:
            tags:
                - FooService
            summary: FooMethod FooService
            operationId: FooService#FooMethod
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/FooMethodRequestBody'
                        example:
                            DateField: "2009-08-25T06:53:12Z"
                            External:
                                Field: Ut mollitia id similique.
                            FieldWithExtension:
                                BarField:
                                    Bar: 12728010016061705013
                            SecondExternal:
                                Field: Corrupti distinctio ut.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/FooMethodRequestBody'
                                example:
                                    - DateField: "1988-07-10T21:21:45Z"
                                      External:
                                        Field: Suscipit rerum aut atque animi ut et.
                                      FieldWithExtension:
                                        BarField:
                                            Bar: 12728010016061705013
                                      SecondExternal:
                                        Field: Quia ab quia rerum.
                                    - DateField: "1988-07-10T21:21:45Z"
                                      External:
                                        Field: Suscipit rerum aut atque animi ut et.
                                      FieldWithExtension:
                                        BarField:
                                            Bar: 12728010016061705013
                                      SecondExternal:
                                        Field: Quia ab quia rerum.
                            example:
                                - DateField: "1988-07-10T21:21:45Z"
                                  External:
                                    Field: Suscipit rerum aut atque animi ut et.
                                  FieldWithExtension:
                                    BarField:
                                        Bar: 12728010016061705013
                                  SecondExternal:
                                    Field: Quia ab quia rerum.
                                - DateField: "1988-07-10T21:21:45Z"
                                  External:
                                    Field: Suscipit rerum aut atque animi ut et.
                                  FieldWithExtension:
                                    BarField:
                                        Bar: 12728010016061705013
                                  SecondExternal:
                                    Field: Quia ab quia rerum.
                                - DateField: "1988-07-10T21:21:45Z"
                                  External:
                                    Field: Suscipit rerum aut atque animi ut et.
                                  FieldWithExtension:
                                    BarField:
                                        Bar: 12728010016061705013
                                  SecondExternal:
                                    Field: Quia ab quia rerum.
                                - DateField: "1988-07-10T21:21:45Z"
                                  External:
                                    Field: Suscipit rerum aut atque animi ut et.
                                  FieldWithExtension:
                                    BarField:
                                        Bar: 12728010016061705013
                                  SecondExternal:
                                    Field: Quia ab quia rerum.
components:
    schemas:
        Bar:
            type: object
            properties:
                Bar:
                    type: integer
                    example: 17921666360832916062
            example:
                Bar: 6287643151275440736
            required:
                - Bar
        ExternalType:
            type: object
            properties:
                Field:
                    type: string
                    example: Dolor expedita neque enim rerum.
            example:
                Field: Iste adipisci qui accusamus.
            required:
                - Field
        FieldWithExtension:
            type: object
            properties:
                BarField:
                    $ref: '#/components/schemas/Bar'
            example:
                BarField:
                    Bar: 12728010016061705013
        FooMethodRequestBody:
            type: object
            properties:
                DateField:
                    type: string
                    example: "1972-04-09T03:02:37Z"
                    format: date-time
                External:
                    $ref: '#/components/schemas/ExternalType'
                FieldWithExtension:
                    $ref: '#/components/schemas/FieldWithExtension'
                SecondExternal:
                    $ref: '#/components/schemas/SecondExternalType'
            example:
                DateField: "1980-06-14T14:53:53Z"
                External:
                    Field: Ut mollitia id similique.
                FieldWithExtension:
                    BarField:
                        Bar: 12728010016061705013
                SecondExternal:
                    Field: Corrupti distinctio ut.
            required:
                - DateField
        SecondExternalType:
            type: object
            properties:
                Field:
                    type: string
                    example: Vel velit quod sint ut rem ea.
            example:
                Field: Vitae qui assumenda suscipit ut mollitia dolores.
tags:
    - name: FooService
