swagger: "2.0"
info:
    title: ""
    version: ""
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /example:
        post:
            tags:
                - FooService
            summary: FooMethod FooService
            operationId: FooService#FooMethod
            parameters:
                - name: FooMethodRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/FooServiceFooMethodRequestBody'
                    required:
                        - DateField
                        - UintField
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/ExampleTypeResponse'
            schemes:
                - http
definitions:
    ExampleTypeResponse:
        title: ExampleTypeResponse
        type: object
        properties:
            DateField:
                type: string
                example: "2013-10-12T18:59:27Z"
                format: date-time
            External:
                $ref: '#/definitions/ExternalTypeResponse'
            SecondExternal:
                $ref: '#/definitions/SecondExternalTypeResponse'
            UintField:
                type: integer
                example: 15605647191505478842
                format: int64
        example:
            DateField: "1997-02-04T09:23:47Z"
            External:
                Field: Rerum aut atque animi.
            SecondExternal:
                Field: Et quisquam quia ab quia rerum.
            UintField: 15935421087944460847
        required:
            - DateField
            - UintField
    ExternalTypeRequestBody:
        title: ExternalTypeRequestBody
        type: object
        properties:
            Field:
                type: string
                example: Occaecati quia tempore quo.
        example:
            Field: Aut et ipsum.
        required:
            - Field
    ExternalTypeResponse:
        title: ExternalTypeResponse
        type: object
        properties:
            Field:
                type: string
                example: Iste iusto dolores asperiores fugit.
        example:
            Field: Sed eligendi voluptatibus aut qui.
        required:
            - Field
    FooServiceFooMethodRequestBody:
        title: FooServiceFooMethodRequestBody
        type: object
        properties:
            DateField:
                type: string
                example: "1992-08-30T18:05:13Z"
                format: date-time
            External:
                $ref: '#/definitions/ExternalTypeRequestBody'
            SecondExternal:
                $ref: '#/definitions/SecondExternalTypeRequestBody'
            UintField:
                type: integer
                example: 254877934337876168
                format: int64
        example:
            DateField: "1977-08-30T18:50:51Z"
            External:
                Field: Ut mollitia id similique.
            SecondExternal:
                Field: Corrupti distinctio ut.
            UintField: 12174973568669703396
        required:
            - DateField
            - UintField
    SecondExternalTypeRequestBody:
        title: SecondExternalTypeRequestBody
        type: object
        properties:
            Field:
                type: string
                example: Ea laboriosam recusandae sit pariatur.
        example:
            Field: Eius eum.
    SecondExternalTypeResponse:
        title: SecondExternalTypeResponse
        type: object
        properties:
            Field:
                type: string
                example: Similique aut qui numquam veritatis repudiandae.
        example:
            Field: Ullam nisi et omnis nihil natus.
